### ISSUE TITLE
your discord

### ISSUE THREAD

**Issue by YasinK2003** [kennyhml/ark-api#1]
could you provide me your discord, i need some help maybe you got the answer

**Comment by kennyhml** [comment]
Please do not create an issue just to ask for my discord. If you have a question regarding coding in general, you can ask in many helpful discords such as TCD [https://discord.gg/code](url)

If its a question regarding this package, you can ask here.

**Comment by YasinK2003** [comment]
Sorry about that it was a suggestion, i instead created a new issue
