### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YasinK2003** [kennyhml/ark-api#2]
for server-query.py

should add the method to query usernames using a2s and if possible even steamid's using another library

**Comment by kennyhml** [comment]
`server_query.py`, as the name indicates, is meant to provide the ability to query a server, if I remember correctly it actually does show connected IDs, but steam is not very accurate with it and shows alot more players than are actually connected. With about 90% of the playerbase playing on Epic Games now anyways, I dont really want to spend time on trying to track steam players.

**Comment by YasinK2003** [comment]
my apologies for my poor suggestion what i was ment to say it that when querying the server it also fetches the usernames connected to it, and session time (both should be possibile with a2s), and if it is possibible adding fetching steamid linked to the users in the server . also for epicplayers trafficsniffing would work.

Since i couldnt find any api that does it, i might aswell suggest it for ark-api.
